/**
 * jin team schema — operator/admin escape hatch for generic Postgres integration.
 *
 * This command provisions the remote Postgres schema that the Postgres
 * integration sink writes to. It is an explicit admin action, not part of
 * the normal developer onboarding story (see BP-Product-Strategy.md).
 *
 * The daemon never runs DDL (BP-06). This command is the only path that
 * creates remote tables, and it requires an explicit operator invocation.
 *
 * Lives under `jin team schema ...` per BP-09 (not top-level `jin schema`).
 */

const INTEGRATION_SCHEMA_VERSION = "2.3";

const POSTGRES_INTEGRATION_DDL = `
-- Jin Postgres Integration Schema v${INTEGRATION_SCHEMA_VERSION}
-- Generated by: jin team schema apply
-- This schema is for the generic Postgres integration sink (BP-06).
-- Jin Team uses a separate backend migration strategy (BP-Product).

CREATE TABLE IF NOT EXISTS jin_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);

INSERT INTO jin_meta (key, value)
  VALUES ('schema_version', '${INTEGRATION_SCHEMA_VERSION}')
  ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value;

CREATE TABLE IF NOT EXISTS jin_conversations (
  id TEXT PRIMARY KEY,
  trace_id TEXT NOT NULL,
  parent_id TEXT DEFAULT '',
  relationship TEXT NOT NULL DEFAULT 'root',
  fork_point INTEGER DEFAULT -1,
  adapter_id TEXT NOT NULL,
  name TEXT,
  cwd TEXT DEFAULT '',
  git_remote TEXT DEFAULT '',
  branch TEXT DEFAULT '',
  model TEXT DEFAULT '',
  started_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  duration_ms INTEGER DEFAULT 0,
  input_tokens INTEGER DEFAULT 0,
  output_tokens INTEGER DEFAULT 0,
  cache_read INTEGER DEFAULT 0,
  cache_write INTEGER DEFAULT 0,
  est_cost DOUBLE PRECISION DEFAULT 0,
  message_count INTEGER DEFAULT 0,
  tool_count INTEGER DEFAULT 0,
  turn_count INTEGER DEFAULT 0,
  source_path TEXT,
  source_format TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS jin_messages (
  id TEXT PRIMARY KEY,
  conversation_id TEXT NOT NULL REFERENCES jin_conversations(id) ON DELETE CASCADE,
  parent_message_id TEXT DEFAULT '',
  role TEXT NOT NULL,
  content TEXT,
  record_type TEXT DEFAULT '',
  model TEXT DEFAULT '',
  sequence INTEGER DEFAULT 0,
  turn INTEGER DEFAULT -1,
  is_sidechain BOOLEAN DEFAULT FALSE,
  input_tokens INTEGER DEFAULT 0,
  output_tokens INTEGER DEFAULT 0,
  cache_read INTEGER DEFAULT 0,
  cache_write INTEGER DEFAULT 0,
  est_cost DOUBLE PRECISION DEFAULT 0,
  thinking_content TEXT DEFAULT '',
  thinking_tokens INTEGER DEFAULT 0,
  timestamp TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS jin_tool_calls (
  id TEXT PRIMARY KEY,
  message_id TEXT NOT NULL REFERENCES jin_messages(id) ON DELETE CASCADE,
  conversation_id TEXT NOT NULL REFERENCES jin_conversations(id) ON DELETE CASCADE,
  name TEXT NOT NULL,
  input TEXT DEFAULT '',
  output TEXT DEFAULT '',
  is_error BOOLEAN DEFAULT FALSE,
  duration_ms INTEGER DEFAULT -1,
  timestamp TIMESTAMPTZ
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_jin_conv_trace ON jin_conversations(trace_id);
CREATE INDEX IF NOT EXISTS idx_jin_conv_parent ON jin_conversations(parent_id);
CREATE INDEX IF NOT EXISTS idx_jin_conv_remote ON jin_conversations(git_remote);
CREATE INDEX IF NOT EXISTS idx_jin_conv_adapter ON jin_conversations(adapter_id);
CREATE INDEX IF NOT EXISTS idx_jin_conv_ended ON jin_conversations(ended_at);

CREATE INDEX IF NOT EXISTS idx_jin_msg_conv ON jin_messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_jin_msg_sequence ON jin_messages(conversation_id, sequence);
CREATE INDEX IF NOT EXISTS idx_jin_msg_timestamp ON jin_messages(timestamp);

CREATE INDEX IF NOT EXISTS idx_jin_tc_conv ON jin_tool_calls(conversation_id);
CREATE INDEX IF NOT EXISTS idx_jin_tc_msg ON jin_tool_calls(message_id);
CREATE INDEX IF NOT EXISTS idx_jin_tc_name ON jin_tool_calls(name);
`;

export async function schemaApplyCommand(opts: {
  connectionString?: string;
  dryRun?: boolean;
}): Promise<void> {
  if (!opts.connectionString) {
    console.log(`
  jin team schema apply — provision the Postgres integration schema (operator)

  This is an explicit operator escape hatch for generic Postgres integrations.
  It creates the tables that the Postgres sink writes to.

  This is NOT part of the normal user onboarding story.
  For workspace/team setups, developers run: jin connect --team=<code>

  Usage:
    jin team schema apply --connection-string="postgres://..."
    jin team schema apply --connection-string="postgres://..." --dry-run

  Flags:
    --connection-string=<url>   Postgres connection string (required)
    --dry-run                   Print the SQL without executing it

  What it does:
    1. Creates jin_meta, jin_conversations, jin_messages, jin_tool_calls
    2. Sets schema_version = ${INTEGRATION_SCHEMA_VERSION} in jin_meta
    3. Creates indexes for common query patterns

  The daemon (jin start) never runs DDL. This command is the only way
  to provision the remote schema for a generic Postgres integration.
`);
    return;
  }

  if (opts.dryRun) {
    console.log("  -- jin team schema apply (dry run)");
    console.log("  -- Target: " + opts.connectionString.replace(/\/\/[^@]*@/, "//***@"));
    console.log("");
    console.log(POSTGRES_INTEGRATION_DDL);
    return;
  }

  console.log("  Applying Postgres integration schema v" + INTEGRATION_SCHEMA_VERSION + "...");

  try {
    const { SQL } = await import("bun");
    const conn = new SQL(opts.connectionString);
    await conn.unsafe(POSTGRES_INTEGRATION_DDL);
    await conn.close();

    const masked = opts.connectionString.replace(/\/\/[^@]*@/, "//***@");
    for (const line of schemaApplySuccessGuidance(masked)) {
      console.log(line);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    console.error("  Error applying schema: " + message);
    console.error("");
    console.error("  Check that:");
    console.error("    - The connection string is correct");
    console.error("    - The database exists");
    console.error("    - The user has CREATE TABLE permissions");
    process.exit(1);
  }
}

export async function schemaCheckCommand(opts: {
  connectionString?: string;
}): Promise<void> {
  if (!opts.connectionString) {
    console.log(`
  jin team schema check — read-only schema version compatibility check

  Usage:
    jin team schema check --connection-string="postgres://..."
`);
    return;
  }

  try {
    const { SQL } = await import("bun");
    const conn = new SQL(opts.connectionString);
    const rows = await conn.unsafe(
      "SELECT value FROM jin_meta WHERE key = 'schema_version' LIMIT 1"
    );
    await conn.close();

    const rowArray = Array.from(rows as Iterable<Record<string, unknown>>);
    if (rowArray.length === 0 || !rowArray[0].value) {
      console.log("  Remote: not initialized (no schema_version in jin_meta)");
      console.log("  Local:  v" + INTEGRATION_SCHEMA_VERSION);
      console.log("  Action: run jin team schema apply");
      return;
    }

    const remoteVersion = String(rowArray[0].value);
    const localMajor = parseInt(INTEGRATION_SCHEMA_VERSION.split(".")[0]);
    const remoteMajor = parseInt(remoteVersion.split(".")[0]);

    console.log("  Remote: v" + remoteVersion + (remoteMajor === localMajor ? " (compatible)" : " (INCOMPATIBLE)"));
    console.log("  Local:  v" + INTEGRATION_SCHEMA_VERSION);

    if (remoteMajor > localMajor) {
      console.log("  Action: update jin (remote schema is newer)");
    } else if (remoteMajor < localMajor) {
      console.log("  Action: run jin team schema apply (remote schema is older)");
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    if (message.toLowerCase().includes("jin_meta") || message.includes("42P01")) {
      console.log("  Remote: not initialized (jin_meta table does not exist)");
      console.log("  Local:  v" + INTEGRATION_SCHEMA_VERSION);
      console.log("  Action: run jin team schema apply");
    } else {
      console.error("  Error checking schema: " + message);
      process.exit(1);
    }
  }
}

export function schemaVersionCommand(): void {
  console.log("  " + INTEGRATION_SCHEMA_VERSION);
}

export function schemaApplySuccessGuidance(maskedConnectionString: string): string[] {
  return [
    "  Schema applied successfully.",
    "",
    "  Next: generate a bridge code for your developers:",
    '    jin team bridge --type=postgres --connection-string="' + maskedConnectionString + '"',
    "",
    "  Or run jin team help for the full operator surface.",
  ];
}

export function getIntegrationDDL(): string {
  return POSTGRES_INTEGRATION_DDL;
}

export function getIntegrationSchemaVersion(): string {
  return INTEGRATION_SCHEMA_VERSION;
}
