export const DEFAULT_INGEST_BATCH_SIZE = 20;
export const DEFAULT_PUSH_BATCH_SIZE = 20;
export const DEFAULT_WATCH_DEBOUNCE_MS = 500;
export const DEFAULT_FIND_CHANGED_TIMEOUT_MS = 60_000;
export const DEFAULT_LOAD_CONVERSATION_TIMEOUT_MS = 30_000;
