#!/usr/bin/env bun
// Reads dashboard/dist/index.html and writes it as an importable TS module.
// Run after `cd dashboard && bun run build` and before `bun build --compile`.

import { existsSync } from "fs";

const htmlPath = "dashboard/dist/index.html";
const outPath = "src/api/_spa.ts";

const placeholder = '<!DOCTYPE html><html><body><h1>jin dashboard</h1><p>Dashboard not built. Run <code>cd dashboard && bun run build</code></p></body></html>';

let html: string;
if (existsSync(htmlPath)) {
  html = await Bun.file(htmlPath).text();
  console.log(`  embedded ${htmlPath} (${(html.length / 1024).toFixed(0)} KB) → ${outPath}`);
} else {
  html = placeholder;
  console.log(`  ${htmlPath} not found, using placeholder → ${outPath}`);
}

// Write as a TS module with the HTML in a template literal
// Escape backticks and ${} in the HTML to avoid breaking the template literal
const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");
await Bun.write(outPath, `// Auto-generated by scripts/embed-spa.ts — do not edit\nexport default \`${escaped}\`;\n`);
